version: "3.9"

networks:
    contestsapp-dev:
        driver: bridge
        
services:
    api:
        container_name: contestsapp-api
        environment: 
            - ConnectionStrings__ContestsDbContext=Host=postgres;Port=5432;Database=contestsdb;Username=postgres;Password=postgres
            - JwtOptions__SecretKey=qweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqwe
            - JwtOptions__ExpiresHours=12
        build:
            context: .
            dockerfile: contests-app.API/Dockerfile
        ports:
            - "5000:8080"
        networks: 
            - contestsapp-dev
        depends_on:
            - postgres_db

    postgres_db:
        container_name: postgres
        image: postgres:latest
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: contestsdb
        ports:
            - "5432:5432"
        networks:
            - contestsapp-dev
        volumes:
            - postgres-data:/var/lib/postgres/data

volumes:
    postgres-data:
    
  