name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_IMAGE_NAME: fatherrtd/contests-app

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd ./contests-app.API
        docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest
    - name: Login no Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Tag and Push Docker Hub
      run: |
        docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKER_IMAGE_NAME }}:dev ${{ env.DOCKER_IMAGE_NAME }}:$GITHUB_RUN_NUMBER
        docker push --all-tags ${{ env.DOCKER_IMAGE_NAME }}
